apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: taskflow
data:
  init.sql: |
    -- Créer la table tasks
    CREATE TABLE IF NOT EXISTS tasks (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        completed BOOLEAN DEFAULT FALSE,
        priority VARCHAR(20) DEFAULT 'medium',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Créer un index pour les performances
    CREATE INDEX IF NOT EXISTS idx_tasks_completed ON tasks(completed);
    CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority);

    -- Générer 1000 tâches de test
    INSERT INTO tasks (title, description, completed, priority)
    SELECT
        'Task ' || generate_series,
        'Description for task ' || generate_series,
        (random() > 0.7)::boolean,  -- 30% de tâches complétées
        CASE
            WHEN random() < 0.2 THEN 'low'
            WHEN random() < 0.7 THEN 'medium'
            ELSE 'high'
        END
    FROM generate_series(1, 1000);

    -- Afficher les statistiques
    SELECT
        COUNT(*) as total_tasks,
        SUM(CASE WHEN completed THEN 1 ELSE 0 END) as completed_tasks,
        SUM(CASE WHEN NOT completed THEN 1 ELSE 0 END) as pending_tasks
    FROM tasks;
