apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: taskflow
  labels:
    app: backend-api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: backend-api
