apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: taskflow
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.taskflow.svc.cluster.local:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: "15s"
        httpMethod: GET
