apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
  namespace: taskflow
spec:
  parallelism: 5
  completions: 5
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: load-generator
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting load generator..."
          API_URL="http://backend-api.taskflow.svc.cluster.local:5000"

          # Boucle infinie de requêtes
          while true; do
            # GET /tasks
            wget -q -O- $API_URL/tasks > /dev/null 2>&1

            # GET /tasks?priority=high
            wget -q -O- $API_URL/tasks?priority=high > /dev/null 2>&1

            # GET /tasks?completed=false
            wget -q -O- $API_URL/tasks?completed=false > /dev/null 2>&1

            # GET /stats
            wget -q -O- $API_URL/stats > /dev/null 2>&1

            # GET /stress (charge CPU)
            wget -q -O- $API_URL/stress?duration=2 > /dev/null 2>&1

            # Petite pause
            sleep 0.1
          done
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"

      volumes:
      - name: tmp
        emptyDir: {}
