apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: myapp
  labels:
    app: database
    component: credentials
type: Opaque
stringData:
  POSTGRES_DB: myapp
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret123
  DATABASE_URL: postgresql://admin:secret123@database:5432/myapp
