apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: myapp
  labels:
    app: database
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Pour minikube, la storageClass par défaut est utilisée
  # En production, spécifier le storageClassName approprié
  # storageClassName: standard
