name: Test Kubernetes Manifests

on:
  push:
    branches: [ main, claude/** ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml-syntax:
    name: Validate YAML Syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: pip install yamllint

      - name: Create yamllint config
        run: |
          cat > .yamllint.yml << 'EOF'
          extends: default
          rules:
            line-length:
              max: 120
              level: warning
            indentation:
              spaces: 2
            comments:
              min-spaces-from-content: 1
            document-start: disable
          EOF

      - name: Run yamllint on TP3
        run: |
          if [ -d "tp3" ]; then
            echo "Validating YAML files in tp3/"
            yamllint -c .yamllint.yml tp3/*.yaml || true
          fi

  validate-kubernetes-manifests:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'

      - name: Install kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/download/v0.6.4/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/
          kubeconform -v

      - name: Validate TP3 manifests with kubeconform
        run: |
          echo "Validating TP3 Kubernetes manifests..."
          for file in tp3/*.yaml; do
            echo "Validating $file"
            kubeconform -summary -output json "$file" || echo "Warning: $file has validation issues"
          done

      - name: Validate TP3 manifests with kubectl dry-run
        run: |
          echo "Testing kubectl dry-run on TP3 manifests..."
          for file in tp3/*.yaml; do
            echo "Dry-run validation: $file"
            kubectl apply --dry-run=client -f "$file" || echo "Warning: $file failed dry-run"
          done

  test-tp3-storage:
    name: Test TP3 - Storage Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: 'v1.28.0'

      - name: Verify Minikube
        run: |
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes

      - name: Test basic pod creation (emptyDir)
        run: |
          echo "Testing 01-emptydir-pod.yaml"
          if [ -f "tp3/01-emptydir-pod.yaml" ]; then
            kubectl apply -f tp3/01-emptydir-pod.yaml
            kubectl wait --for=condition=Ready pod/emptydir-pod --timeout=60s || true
            kubectl get pods
            kubectl describe pod emptydir-pod || true
            kubectl delete -f tp3/01-emptydir-pod.yaml --ignore-not-found=true
          fi

      - name: Test PersistentVolume
        run: |
          echo "Testing 02-persistent-volume.yaml"
          if [ -f "tp3/02-persistent-volume.yaml" ]; then
            kubectl apply -f tp3/02-persistent-volume.yaml
            kubectl get pv
            kubectl describe pv my-pv || true
          fi

      - name: Test PersistentVolumeClaim
        run: |
          echo "Testing 03-persistent-volume-claim.yaml"
          if [ -f "tp3/03-persistent-volume-claim.yaml" ]; then
            kubectl apply -f tp3/03-persistent-volume-claim.yaml
            sleep 5
            kubectl get pvc
            kubectl describe pvc my-pvc || true
          fi

      - name: Test Pod with PVC
        run: |
          echo "Testing 04-pod-with-pvc.yaml"
          if [ -f "tp3/04-pod-with-pvc.yaml" ]; then
            kubectl apply -f tp3/04-pod-with-pvc.yaml
            kubectl wait --for=condition=Ready pod/pod-with-pvc --timeout=90s || true
            kubectl get pods
            kubectl describe pod pod-with-pvc || true
          fi

      - name: Cleanup TP3 resources
        if: always()
        run: |
          kubectl delete pod --all --ignore-not-found=true
          kubectl delete pvc --all --ignore-not-found=true
          kubectl delete pv --all --ignore-not-found=true

  validate-readme-manifests:
    name: Extract and Validate README Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Extract YAML from README files
        run: |
          python3 << 'PYTHON_SCRIPT'
          import re
          import yaml
          import os
          from pathlib import Path

          def extract_yaml_blocks(readme_path):
              """Extract YAML blocks from a markdown file."""
              with open(readme_path, 'r', encoding='utf-8') as f:
                  content = f.read()

              # Find all YAML code blocks
              pattern = r'```yaml\n(.*?)```'
              matches = re.findall(pattern, content, re.DOTALL)
              return matches

          def validate_yaml(yaml_content, source):
              """Validate YAML syntax."""
              try:
                  # Try to parse as YAML
                  docs = list(yaml.safe_load_all(yaml_content))

                  # Check for Kubernetes resources
                  k8s_count = 0
                  for doc in docs:
                      if doc and isinstance(doc, dict):
                          if 'apiVersion' in doc and 'kind' in doc:
                              k8s_count += 1

                  return True, k8s_count
              except yaml.YAMLError as e:
                  return False, str(e)

          # Process all TP README files
          tps = ['tp1', 'tp2', 'tp3', 'tp4', 'tp5', 'tp6']
          total_yaml = 0
          total_k8s = 0
          errors = []

          for tp in tps:
              readme_path = Path(tp) / 'README.md'
              if not readme_path.exists():
                  continue

              print(f"\n{'='*60}")
              print(f"Processing {readme_path}")
              print(f"{'='*60}")

              yaml_blocks = extract_yaml_blocks(readme_path)
              print(f"Found {len(yaml_blocks)} YAML blocks")

              for i, yaml_content in enumerate(yaml_blocks, 1):
                  total_yaml += 1
                  valid, result = validate_yaml(yaml_content, f"{tp}/README.md block {i}")

                  if valid:
                      k8s_count = result
                      if k8s_count > 0:
                          total_k8s += k8s_count
                          print(f"  ✓ Block {i}: Valid YAML with {k8s_count} Kubernetes resource(s)")
                  else:
                      error_msg = f"{tp}/README.md block {i}: {result}"
                      errors.append(error_msg)
                      print(f"  ✗ Block {i}: Invalid YAML - {result}")

          print(f"\n{'='*60}")
          print(f"Summary")
          print(f"{'='*60}")
          print(f"Total YAML blocks: {total_yaml}")
          print(f"Total Kubernetes resources: {total_k8s}")
          print(f"Errors: {len(errors)}")

          if errors:
              print("\nErrors found:")
              for error in errors[:10]:  # Show first 10 errors
                  print(f"  - {error}")

          # Don't fail the job on validation errors, just report
          print(f"\n✓ README manifest extraction completed")
          PYTHON_SCRIPT

  lint-readme:
    name: Lint README Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check README files exist
        run: |
          echo "Checking README files..."
          for tp in tp1 tp2 tp3 tp4 tp5 tp6; do
            if [ -f "$tp/README.md" ]; then
              echo "✓ $tp/README.md exists ($(wc -l < "$tp/README.md") lines)"
            else
              echo "✗ $tp/README.md missing"
              exit 1
            fi
          done

      - name: Check for broken links
        run: |
          echo "Checking for common markdown issues..."
          # Check for unclosed code blocks
          for readme in tp*/README.md README.md; do
            if [ -f "$readme" ]; then
              backticks=$(grep -c '```' "$readme" || true)
              if [ $((backticks % 2)) -ne 0 ]; then
                echo "Warning: $readme may have unclosed code blocks"
              else
                echo "✓ $readme: code blocks look good"
              fi
            fi
          done
