# Exemple d'architecture complète à 3 tiers
# Frontend (LoadBalancer) -> Backend API (ClusterIP) -> Database (ClusterIP)
# Démontre l'utilisation appropriée de chaque type de service

# Base de données (ClusterIP - interne uniquement)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "secretpassword"
        - name: POSTGRES_DB
          value: "appdb"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ClusterIP  # Accessible uniquement depuis le cluster
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
---
# Backend API (ClusterIP - appelé par le frontend)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: httpd:2.4-alpine  # Remplacer par votre API réelle
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: "database-service"  # Utilise le nom du service
        - name: DATABASE_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  type: ClusterIP  # Interne, appelé uniquement par le frontend
  selector:
    app: api
  ports:
  - port: 8080
    targetPort: 80
---
# Frontend (LoadBalancer - accessible publiquement)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://backend-api-service:8080"  # Utilise le nom du service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # Accessible depuis Internet
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
