# Exemple de Service ClusterIP - Base de données Redis
# Ce service est accessible uniquement depuis l'intérieur du cluster
# Cas d'usage : Backend database, cache interne, message queue

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP  # Accessible uniquement depuis l'intérieur du cluster
  selector:
    app: redis
    tier: backend
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
