# Exemple de Service NodePort - Application de développement
# Ce service est accessible depuis l'extérieur via <NodeIP>:<NodePort>
# Cas d'usage : Applications dev/test, débogage, démos

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      env: dev
  template:
    metadata:
      labels:
        app: webapp
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: webapp-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Application de Développement</title></head>
    <body>
      <h1>🚀 Application NodePort</h1>
      <p>Cette application est exposée via NodePort et accessible depuis l'extérieur du cluster.</p>
      <p>Hostname: <span id="hostname"></span></p>
      <script>
        fetch('/hostname.txt').then(r => r.text()).then(h => {
          document.getElementById('hostname').textContent = h || window.location.hostname;
        }).catch(() => {
          document.getElementById('hostname').textContent = window.location.hostname;
        });
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
spec:
  type: NodePort
  selector:
    app: webapp
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100  # Port fixe pour un accès prévisible
