# Exemples de StorageClasses sécurisées pour différents environnements
# Ce fichier contient des exemples de configurations pour différents backends de stockage

---
# StorageClass pour AWS EBS avec chiffrement KMS
# Use case: Production sur AWS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-encrypted-gp3
  labels:
    environment: production
    provider: aws
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    description: "Encrypted GP3 SSD storage for production workloads"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"  # Chiffrement obligatoire
  kmsKeyId: "arn:aws:kms:us-east-1:123456789012:key/abcd1234-a123-456a-a12b-a123b4567890"
  # Tags AWS pour la facturation et l'organisation
  tagSpecification_1: "Environment=Production"
  tagSpecification_2: "ManagedBy=Kubernetes"
  tagSpecification_3: "CostCenter=Engineering"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer  # Attendre le scheduling du pod
reclaimPolicy: Retain  # Conserver les données en cas de suppression du PVC
mountOptions:
  - noatime  # Pas de mise à jour de access time pour de meilleures performances

---
# StorageClass pour Azure Disk avec chiffrement
# Use case: Production sur Azure
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-encrypted-premium
  labels:
    environment: production
    provider: azure
provisioner: disk.csi.azure.com
parameters:
  storageaccounttype: Premium_LRS  # Premium SSD localement redondant
  kind: Managed
  # Chiffrement avec clé gérée par le client (CMK)
  diskEncryptionSetID: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.Compute/diskEncryptionSets/myDiskEncryptionSet"
  # Tags Azure
  tags: "environment=production,managedby=kubernetes,costcenter=engineering"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
mountOptions:
  - barrier=1
  - noatime

---
# StorageClass pour GCP Persistent Disk avec chiffrement CMEK
# Use case: Production sur GCP
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-encrypted-ssd
  labels:
    environment: production
    provider: gcp
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  replication-type: regional-pd  # Réplication régionale pour HA
  # Chiffrement avec clé gérée par le client
  disk-encryption-kms-key: "projects/my-project/locations/us-central1/keyRings/my-keyring/cryptoKeys/my-key"
  # Labels GCP
  labels: "environment=production,managedby=kubernetes"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
# StorageClass pour Longhorn avec réplication et chiffrement
# Use case: Production on-premise avec HA
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-encrypted-ha
  labels:
    environment: production
    provider: longhorn
    tier: high-availability
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"  # 3 réplicas pour haute disponibilité
  staleReplicaTimeout: "2880"  # 48 heures
  dataLocality: "best-effort"  # Préférer le nœud local pour les lectures
  fromBackup: ""
  fsType: "ext4"
  # Sélecteurs pour cibler des nœuds spécifiques
  diskSelector: "ssd,fast"
  nodeSelector: "storage,production"
  # Chiffrement (nécessite la configuration de Longhorn)
  encrypted: "true"
  # Paramètres de performance
  numberOfReplicas: "3"
  replicaAutoBalance: "best-effort"
  # Snapshot récurrents
  recurringJobSelector: '[{"name":"snapshot-daily","isGroup":true}]'
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain

---
# StorageClass pour Ceph RBD (via Rook) avec réplication
# Use case: Enterprise on-premise avec scale
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block-encrypted
  labels:
    environment: production
    provider: rook-ceph
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-ceph
  pool: replicapool  # Pool avec réplication
  imageFormat: "2"
  imageFeatures: layering,exclusive-lock,object-map,fast-diff
  # Chiffrement LUKS
  encrypted: "true"
  encryptionKMSID: "vault"
  # CSI driver parameters
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
mountOptions:
  - discard  # Support TRIM pour SSD

---
# StorageClass pour NFS avec provisioner
# Use case: Stockage partagé ReadWriteMany
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-shared-secure
  labels:
    environment: production
    provider: nfs
    access-mode: rwx
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server.internal.company.com
  share: /exports/kubernetes/shared
  # Paramètres de montage pour la sécurité et la performance
  mountOptions: "nfsvers=4.1,hard,intr,rsize=1048576,wsize=1048576,timeo=600"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard  # Réessayer en cas d'échec réseau
  - intr  # Interruptible
  - rsize=1048576  # Read size 1MB
  - wsize=1048576  # Write size 1MB
  - timeo=600  # Timeout 60s
  - retrans=2  # Nombre de retransmissions

---
# StorageClass locale pour cache haute performance
# Use case: Cache Redis, données temporaires
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd-cache
  labels:
    environment: production
    provider: local
    performance: high
    data-type: ephemeral
provisioner: kubernetes.io/no-provisioner  # Pas de provisionnement automatique
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete  # Supprimer les données car c'est du cache

---
# StorageClass pour développement/test (non sécurisée, pas de chiffrement)
# Use case: Environnement de développement uniquement
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dev-standard
  labels:
    environment: development
    cost: low
  annotations:
    description: "Standard storage for development - NO ENCRYPTION - NOT FOR PRODUCTION"
provisioner: k8s.io/minikube-hostpath  # Pour minikube
parameters:
  type: pd-standard
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Delete  # Supprimer automatiquement pour économiser

---
# StorageClass pour logs et données peu sensibles
# Use case: Logs d'application, données analytiques
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-logs-storage
  labels:
    environment: production
    performance: standard
    cost: optimized
provisioner: ebs.csi.aws.com
parameters:
  type: st1  # Throughput Optimized HDD (moins cher)
  encrypted: "true"  # Toujours chiffrer même pour les logs
  kmsKeyId: "arn:aws:kms:us-east-1:123456789012:key/logs-key-id"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete  # Les logs peuvent être supprimés
mountOptions:
  - noatime

---
# StorageClass avec snapshot automatique
# Use case: Bases de données critiques avec backups fréquents
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-with-snapshots
  labels:
    environment: production
    backup: enabled
    tier: critical
  annotations:
    snapshot.storage.kubernetes.io/snapshot-class: "daily-snapshots"
provisioner: ebs.csi.aws.com
parameters:
  type: io2  # Provisioned IOPS SSD
  iops: "10000"
  encrypted: "true"
  kmsKeyId: "arn:aws:kms:us-east-1:123456789012:key/database-key-id"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain  # JAMAIS supprimer les données de prod

---
# VolumeSnapshotClass pour les snapshots quotidiens
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: daily-snapshots
  labels:
    schedule: daily
    retention: 30days
driver: ebs.csi.aws.com
deletionPolicy: Retain  # Conserver les snapshots même si le VolumeSnapshot est supprimé
parameters:
  # Tags pour identifier les snapshots
  tagSpecification_1: "Type=Automated"
  tagSpecification_2: "Schedule=Daily"
  tagSpecification_3: "Retention=30Days"

---
# ResourceQuota pour limiter l'utilisation du stockage par namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota-production
  namespace: production
spec:
  hard:
    # Limite totale de stockage
    requests.storage: "1Ti"

    # Limite par StorageClass
    requests.storage.storageclass.storage.k8s.io/aws-encrypted-gp3: "500Gi"
    requests.storage.storageclass.storage.k8s.io/database-with-snapshots: "300Gi"
    requests.storage.storageclass.storage.k8s.io/hdd-logs-storage: "200Gi"

    # Nombre de PVC
    persistentvolumeclaims: "50"

    # Limite par StorageClass
    persistentvolumeclaims.storageclass.storage.k8s.io/database-with-snapshots: "10"

---
# LimitRange pour définir les tailles min/max des PVC
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits-production
  namespace: production
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 500Gi  # Taille max par PVC
    min:
      storage: 1Gi    # Taille min par PVC
    default:
      storage: 10Gi   # Taille par défaut si non spécifié
    defaultRequest:
      storage: 10Gi
