apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-app-pdb
spec:
  minAvailable: 2  # Minimum 2 pods doivent rester disponibles
  selector:
    matchLabels:
      app: my-app
---
# Alternative: maxUnavailable
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-app-pdb-max
spec:
  maxUnavailable: 1  # Maximum 1 pod peut être indisponible
  selector:
    matchLabels:
      app: my-app
