# PRÉREQUIS: Ce ServiceMonitor nécessite un Service avec un port nommé 'metrics'
# Exemple de Service requis:
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app
#   labels:
#     app: my-app
# spec:
#   selector:
#     app: my-app
#   ports:
#   - name: metrics
#     port: 9090
#     targetPort: 9090
#   - name: http
#     port: 80
#     targetPort: 80
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-app-metrics
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
