# Exemples de Taints et Tolerations pour le TP9

# Pour appliquer les taints, utilisez ces commandes :
# kubectl taint nodes worker1 dedicated=database:NoSchedule
# kubectl taint nodes worker2 gpu=nvidia:NoSchedule
# kubectl taint nodes worker3 maintenance=true:NoExecute

---
# Exemple 1 : Toleration simple avec Equal
apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: postgres
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"
  containers:
  - name: postgres
    image: postgres:15-alpine
    env:
    - name: POSTGRES_PASSWORD
      value: "mysecretpassword"
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"

---
# Exemple 2 : Toleration avec Exists (tolère toute valeur)
apiVersion: v1
kind: Pod
metadata:
  name: admin-debug-pod
spec:
  tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: admin
    image: busybox:latest
    command: ['sh', '-c', 'sleep 3600']

---
# Exemple 3 : Tolérer tous les taints (super admin)
apiVersion: v1
kind: Pod
metadata:
  name: super-admin-pod
spec:
  tolerations:
  - operator: "Exists"
  containers:
  - name: admin
    image: nicolaka/netshoot
    command: ['sh', '-c', 'sleep infinity']

---
# Exemple 4 : Deployment pour nœuds dédiés base de données
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cluster
  labels:
    app: postgres
    workload: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # NodeSelector pour forcer sur les nœuds database
      nodeSelector:
        workload: database
      # Toleration pour accepter le taint
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "database"
        effect: "NoSchedule"
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"

---
# Exemple 5 : Job GPU avec toleration
apiVersion: batch/v1
kind: Job
metadata:
  name: ml-training-job
  labels:
    workload: ml
spec:
  template:
    metadata:
      labels:
        workload: ml
    spec:
      restartPolicy: Never
      nodeSelector:
        gpu: nvidia
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: ml-training
        image: tensorflow/tensorflow:latest-gpu
        command: ["python", "train.py"]
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "4"

---
# Exemple 6 : NoExecute avec tolerationSeconds
apiVersion: v1
kind: Pod
metadata:
  name: maintenance-aware-pod
spec:
  tolerations:
  # Tolère la maintenance pendant 1 heure
  - key: "maintenance"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
    tolerationSeconds: 3600
  containers:
  - name: app
    image: nginx:alpine
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"

---
# Exemple 7 : Deployment avec tolerations multiples
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexible-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flexible
  template:
    metadata:
      labels:
        app: flexible
    spec:
      tolerations:
      # Tolère les nœuds en maintenance (temporairement)
      - key: "maintenance"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      # Tolère les nœuds SSD
      - key: "disktype"
        operator: "Equal"
        value: "ssd"
        effect: "NoSchedule"
      # Tolère PreferNoSchedule pour GPU
      - key: "gpu"
        operator: "Exists"
        effect: "PreferNoSchedule"
      containers:
      - name: app
        image: myapp:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"

---
# Exemple 8 : DaemonSet avec toleration pour tous les nœuds
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: kube-system
  labels:
    app: log-collector
spec:
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      # DaemonSet doit tourner partout, même sur control planes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      # Tolère aussi tous les autres taints
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd:latest
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

---
# Exemple 9 : StatefulSet pour nœuds SSD avec affinity + toleration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      # Combiner affinity et toleration pour contrôle maximal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - elasticsearch
            topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "elasticsearch"
        effect: "NoSchedule"
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: discovery.type
          value: "single-node"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"

---
# Exemple 10 : CronJob qui tolère les nœuds de maintenance
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "0 2 * * *"  # Tous les jours à 2h du matin
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          tolerations:
          # Peut s'exécuter même sur des nœuds en maintenance
          - key: "maintenance"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "maintenance"
            operator: "Exists"
            effect: "NoExecute"
          containers:
          - name: backup
            image: backup-tool:latest
            command: ["/bin/sh"]
            args:
            - -c
            - |
              echo "Starting backup..."
              # Script de backup ici
              echo "Backup completed"
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
