apiVersion: v1
kind: Pod
metadata:
  name: multi-log-pod
spec:
  containers:
  - name: frontend
    image: busybox
    command: ["/bin/sh"]
    args:
      - -c
      - >
        while true; do
          echo "[FRONTEND] Handling request at $(date)";
          sleep 3;
        done

  - name: backend
    image: busybox
    command: ["/bin/sh"]
    args:
      - -c
      - >
        while true; do
          echo "[BACKEND] Processing data at $(date)";
          sleep 5;
        done

  - name: cache
    image: busybox
    command: ["/bin/sh"]
    args:
      - -c
      - >
        while true; do
          echo "[CACHE] Cache hit/miss at $(date)";
          sleep 4;
        done
