apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buggy-app
  template:
    metadata:
      labels:
        app: buggy-app
    spec:
      containers:
      - name: app
        image: busybox
        command: ["/bin/sh"]
        args:
          - -c
          - >
            echo "Starting application...";
            sleep 10;
            echo "Application running";
            sleep 20;
            echo "ERROR: Out of memory!";
            exit 1
