apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-run-
  namespace: default
spec:
  pipelineRef:
    name: ci-pipeline
  params:
    - name: git-url
      # TODO: Remplacer par l'URL de votre repository
      value: "https://github.com/votre-username/votre-repo.git"
    - name: git-revision
      value: "main"
    - name: image-name
      value: "localhost:5000/my-app"  # Registry local
    - name: image-tag
      value: "latest"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
