apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
  namespace: default
spec:
  description: Pipeline CD - Déploiement sur Kubernetes
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: release-name
      type: string
      default: my-app
    - name: chart-path
      type: string
      default: 01-helm/my-app
    - name: namespace
      type: string
      default: production
    - name: image-repository
      type: string
    - name: image-tag
      type: string
    - name: deployment-name
      type: string
      default: my-app

  workspaces:
    - name: shared-workspace

  tasks:
    # Task 1: Cloner le repository (pour les charts Helm)
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    # Task 2: Déployer avec Helm
    - name: deploy-with-helm
      taskRef:
        name: helm-deploy
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: release-name
          value: $(params.release-name)
        - name: chart-path
          value: $(params.chart-path)
        - name: namespace
          value: $(params.namespace)
        - name: image-repository
          value: $(params.image-repository)
        - name: image-tag
          value: $(params.image-tag)

    # Task 3: Vérifier le déploiement
    - name: verify-deployment
      taskRef:
        name: kubectl-verify
      runAfter:
        - deploy-with-helm
      params:
        - name: deployment-name
          value: $(params.deployment-name)
        - name: namespace
          value: $(params.namespace)
