apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: default
spec:
  description: Pipeline CI complet - Tests et Build
  params:
    - name: git-url
      type: string
      description: URL du repository Git
    - name: git-revision
      type: string
      default: main
    - name: image-name
      type: string
      description: Nom de l'image Docker (sans tag)
    - name: image-tag
      type: string
      default: latest

  workspaces:
    - name: shared-workspace
      description: Workspace partagé pour le code source

  tasks:
    # Task 1: Cloner le repository
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    # Task 2: Tests npm (dépend de fetch-repository)
    - name: run-tests
      taskRef:
        name: npm-test
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: node-version
          value: "18"

    # Task 3: Build Docker (dépend de run-tests)
    - name: build-image
      taskRef:
        name: docker-build
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image
          value: "$(params.image-name):$(params.image-tag)"

    # Task 4: Scan de sécurité (dépend de build-image)
    - name: security-scan
      taskRef:
        name: trivy-scan
      runAfter:
        - build-image
      params:
        - name: image
          value: "$(params.image-name):$(params.image-tag)"
