apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default

  source:
    # IMPORTANT: Remplacer par l'URL de votre repository GitOps réel
    repoURL: https://github.com/username/my-gitops-repo.git  # À PERSONNALISER
    targetRevision: HEAD
    path: helm/my-app
    helm:
      releaseName: my-app
      values: |
        replicaCount: 3
        image:
          tag: "v1.0.0"
        resources:
          limits:
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
