apiVersion: v2
name: my-app
description: Une application web simple
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - web
  - demo
maintainers:
  - name: Your Name
    email: your.email@example.com
